import type {
  Vehicle,
  Customer,
  Order,
  Quotation,
  Inventory,
  VehicleRequest,
  TestDrive,
  Dealer,
  Promotion,
} from "@/lib/types"

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: "v1",
    modelName: "Model S Plaid",
    brand: "Tesla",
    year: 2024,
    basePrice: 89990,
    status: "available",
    createdAt: new Date().toISOString(),
    images: ["/tesla-model-s-front.jpg", "/tesla-model-s-interior.jpg"],
    variants: [
      { id: "var1", name: "Long Range", additionalPrice: 0, features: ["Dual Motor", "405mi Range"] },
      { id: "var2", name: "Plaid", additionalPrice: 15000, features: ["Tri Motor", "1.99s 0-60"] },
    ],
    colors: [
      { id: "c1", name: "Pearl White", hexCode: "#ffffff", additionalPrice: 0 },
      { id: "c2", name: "Solid Black", hexCode: "#000000", additionalPrice: 1500 },
      { id: "c3", name: "Deep Blue", hexCode: "#0000ff", additionalPrice: 1500 },
    ],
    specifications: {
      batteryCapacity: "100 kWh",
      range: "396 mi",
      motorPower: "1020 hp",
      chargingTime: "15 min (Supercharger)",
      topSpeed: "200 mph",
      acceleration: "1.99s",
    },
  },
  {
    id: "v2",
    modelName: "Air Sapphire",
    brand: "Lucid",
    year: 2024,
    basePrice: 249000,
    status: "available",
    createdAt: new Date().toISOString(),
    images: ["/lucid-air-sapphire.jpg"],
    variants: [
      { id: "var3", name: "Standard", additionalPrice: 0, features: ["Sapphire Blue", "Carbon Ceramic Brakes"] },
    ],
    colors: [{ id: "c4", name: "Sapphire Blue", hexCode: "#0f172a", additionalPrice: 0 }],
    specifications: {
      batteryCapacity: "118 kWh",
      range: "427 mi",
      motorPower: "1234 hp",
      chargingTime: "20 min",
      topSpeed: "205 mph",
      acceleration: "1.89s",
    },
  },
  {
    id: "v3",
    modelName: "Taycan Turbo S",
    brand: "Porsche",
    year: 2024,
    basePrice: 194900,
    status: "available",
    createdAt: new Date().toISOString(),
    images: ["/porsche-taycan-turbo-s.jpg"],
    variants: [
      { id: "var4", name: "Turbo", additionalPrice: 0, features: ["670 hp"] },
      { id: "var5", name: "Turbo S", additionalPrice: 35000, features: ["938 hp", "Ceramic Brakes"] },
    ],
    colors: [
      { id: "c5", name: "White", hexCode: "#ffffff", additionalPrice: 0 },
      { id: "c6", name: "Carmine Red", hexCode: "#990000", additionalPrice: 3150 },
    ],
    specifications: {
      batteryCapacity: "93.4 kWh",
      range: "278 mi",
      motorPower: "938 hp",
      chargingTime: "22.5 min",
      topSpeed: "161 mph",
      acceleration: "2.6s",
    },
  },
]

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: "cust1",
    name: "Nguyen Van A",
    email: "nguyenvana@example.com",
    phone: "0901234567",
    address: "123 Le Loi, District 1, HCMC",
    idNumber: "079123456789",
    dateOfBirth: "1990-01-01",
    dealerId: "dealer1",
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "cust2",
    name: "Tran Thi B",
    email: "tranthib@example.com",
    phone: "0909876543",
    address: "456 Nguyen Hue, District 1, HCMC",
    idNumber: "079987654321",
    dateOfBirth: "1995-05-15",
    dealerId: "dealer1",
    createdAt: "2024-02-20T14:30:00Z",
  },
]

export const MOCK_ORDERS: Order[] = [
  {
    id: "ord1",
    quotationId: "qt1",
    customerId: "cust1",
    vehicleId: "v1",
    totalAmount: 104990,
    paymentMethod: "installment",
    status: "vehicle_allocated",
    dealerId: "dealer1",
    createdBy: "staff1",
    createdAt: "2024-03-10T09:00:00Z",
  },
  {
    id: "ord2",
    quotationId: "qt2",
    customerId: "cust2",
    vehicleId: "v3",
    totalAmount: 194900,
    paymentMethod: "cash",
    status: "pending",
    dealerId: "dealer1",
    createdBy: "staff1",
    createdAt: "2024-03-12T11:15:00Z",
  },
]

export const MOCK_QUOTATIONS: Quotation[] = [
  {
    id: "qt1",
    customerId: "cust1",
    vehicleId: "v1",
    variantId: "var2",
    colorId: "c1",
    basePrice: 89990,
    variantPrice: 15000,
    colorPrice: 0,
    dealerDiscount: 0,
    promotionDiscount: 0,
    finalPrice: 104990,
    validUntil: "2024-04-10T00:00:00Z",
    status: "accepted",
    createdBy: "staff1",
    createdAt: "2024-03-09T08:00:00Z",
  },
  {
    id: "qt2",
    customerId: "cust2",
    vehicleId: "v3",
    variantId: "var4",
    colorId: "c5",
    basePrice: 194900,
    variantPrice: 0,
    colorPrice: 0,
    dealerDiscount: 0,
    promotionDiscount: 0,
    finalPrice: 194900,
    validUntil: "2024-04-12T00:00:00Z",
    status: "sent",
    createdBy: "staff1",
    createdAt: "2024-03-12T10:00:00Z",
  },
]

export const MOCK_INVENTORY: Inventory[] = [
  {
    id: "inv1",
    vehicleId: "v1",
    variantId: "var1",
    colorId: "c1",
    dealerId: "dealer1",
    quantity: 2,
    status: "available",
    updatedAt: "2024-03-15T08:00:00Z",
  },
  {
    id: "inv2",
    vehicleId: "v1",
    variantId: "var2",
    colorId: "c2",
    dealerId: "dealer1",
    quantity: 1,
    status: "reserved",
    updatedAt: "2024-03-14T10:00:00Z",
  },
  {
    id: "inv3",
    vehicleId: "v2",
    variantId: "var3",
    colorId: "c4",
    dealerId: null, // Central Inventory
    quantity: 15,
    status: "available",
    updatedAt: "2024-03-15T09:00:00Z",
  },
  {
    id: "inv4",
    vehicleId: "v3",
    variantId: "var4",
    colorId: "c5",
    dealerId: null, // Central Inventory
    quantity: 8,
    status: "available",
    updatedAt: "2024-03-15T09:00:00Z",
  },
]

export const MOCK_REQUESTS: VehicleRequest[] = [
  {
    id: "req1",
    dealerId: "dealer1",
    vehicleId: "v2",
    variantId: "var3",
    colorId: "c4",
    quantity: 2,
    status: "pending",
    requestedBy: "staff1",
    createdAt: "2024-03-16T10:00:00Z",
  },
  {
    id: "req2",
    dealerId: "dealer1",
    vehicleId: "v3",
    variantId: "var5",
    colorId: "c6",
    quantity: 1,
    status: "approved",
    requestedBy: "staff1",
    approvedBy: "evm_staff1",
    createdAt: "2024-03-14T15:00:00Z",
  },
]

export const MOCK_TEST_DRIVES: TestDrive[] = [
  {
    id: "td1",
    customerId: "cust1",
    vehicleId: "v1",
    date: "2024-03-25",
    time: "10:00",
    status: "scheduled",
    dealerId: "dealer1",
    createdAt: "2024-03-20T09:00:00Z",
  },
  {
    id: "td2",
    customerId: "cust2",
    vehicleId: "v3",
    date: "2024-03-26",
    time: "14:30",
    status: "completed",
    notes: "Customer loved the acceleration.",
    dealerId: "dealer1",
    createdAt: "2024-03-21T11:00:00Z",
  },
]

export const MOCK_DEALERS: Dealer[] = [
  {
    id: "dealer1",
    name: "EV Dealer Saigon Center",
    code: "D001",
    address: "123 Le Loi, District 1, HCMC",
    phone: "02838234567",
    email: "saigon@evdealer.com",
    managerName: "Le Van Quan",
    status: "active",
    region: "South",
    createdAt: "2023-01-01T00:00:00Z",
  },
  {
    id: "dealer2",
    name: "EV Dealer Hanoi West",
    code: "D002",
    address: "456 Pham Hung, Nam Tu Liem, Hanoi",
    phone: "02437654321",
    email: "hanoi@evdealer.com",
    managerName: "Tran Thi Quan",
    status: "active",
    region: "North",
    createdAt: "2023-02-15T00:00:00Z",
  },
]

export const MOCK_PROMOTIONS: Promotion[] = [
  {
    id: "promo1",
    name: "Summer Sale 2024",
    description: "Get $2,000 off on all Model S variants",
    discountType: "fixed_amount",
    discountValue: 2000,
    startDate: "2024-06-01",
    endDate: "2024-08-31",
    status: "scheduled",
    applicableVehicles: ["v1"],
  },
  {
    id: "promo2",
    name: "Early Bird Special",
    description: "10% discount for first 50 orders",
    discountType: "percentage",
    discountValue: 10,
    startDate: "2024-01-01",
    endDate: "2024-03-31",
    status: "active",
  },
]
